import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0016_create_missing_business_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Customer',
                    fields=[
                        ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('customer_code', models.CharField(max_length=50, unique=True)),
                        ('full_name', models.CharField(max_length=255)),
                        ('gender', models.CharField(default='unknown', max_length=20)),
                        ('birthday', models.DateField(blank=True, null=True)),
                        ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                        ('loyalty_points', models.IntegerField(default=0)),
                        ('customer_rank', models.CharField(default='standard', max_length=50)),
                        ('total_orders', models.IntegerField(default=0)),
                        ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                        ('preferred_size', models.CharField(blank=True, max_length=50, null=True)),
                        ('preferred_color', models.CharField(blank=True, max_length=100, null=True)),
                        ('preferred_style', models.CharField(blank=True, max_length=100, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='products.storeuser')),
                    ],
                    options={'db_table': 'customers'},
                ),
                migrations.CreateModel(
                    name='Cart',
                    fields=[
                        ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.customer')),
                    ],
                    options={'db_table': 'carts'},
                ),
                migrations.CreateModel(
                    name='UserSession',
                    fields=[
                        ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('jwt_id', models.CharField(max_length=128, unique=True)),
                        ('refresh_token_hash', models.CharField(blank=True, max_length=255, null=True)),
                        ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                        ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                        ('expires_at', models.DateTimeField()),
                        ('revoked_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='products.storeuser')),
                    ],
                    options={'db_table': 'user_sessions'},
                ),
                migrations.CreateModel(
                    name='StaffProfile',
                    fields=[
                        ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('staff_code', models.CharField(max_length=50, unique=True)),
                        ('full_name', models.CharField(max_length=255)),
                        ('position', models.CharField(max_length=100)),
                        ('department', models.CharField(max_length=100)),
                        ('status', models.CharField(default='active', max_length=30)),
                        ('hire_date', models.DateField(blank=True, null=True)),
                        ('can_process_orders', models.BooleanField(default=True)),
                        ('can_manage_inventory', models.BooleanField(default=True)),
                        ('can_handle_returns', models.BooleanField(default=True)),
                        ('can_moderate_reviews', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='products.storeuser')),
                    ],
                    options={'db_table': 'staffs'},
                ),
                migrations.CreateModel(
                    name='AdminProfile',
                    fields=[
                        ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('admin_code', models.CharField(max_length=50, unique=True)),
                        ('full_name', models.CharField(max_length=255)),
                        ('level', models.CharField(default='admin', max_length=20)),
                        ('can_manage_users', models.BooleanField(default=True)),
                        ('can_manage_catalog', models.BooleanField(default=True)),
                        ('can_manage_orders', models.BooleanField(default=True)),
                        ('can_manage_payments', models.BooleanField(default=True)),
                        ('can_manage_ai', models.BooleanField(default=True)),
                        ('can_view_reports', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='products.storeuser')),
                    ],
                    options={'db_table': 'admins'},
                ),
                migrations.CreateModel(
                    name='PrecomputedRecommendation',
                    fields=[
                        ('rec_id', models.BigAutoField(db_column='recommendation_id', primary_key=True, serialize=False)),
                        ('score', models.FloatField()),
                        ('rank', models.IntegerField(db_column='recommendation_rank')),
                        ('reason', models.TextField(blank=True)),
                        ('algorithm_type', models.CharField(choices=[('collaborative_filtering', 'Collaborative Filtering'), ('content_based', 'Content Based'), ('hybrid', 'Hybrid')], max_length=40)),
                        ('generated_at', models.DateTimeField(auto_now_add=True)),
                        ('expires_at', models.DateTimeField(blank=True, null=True)),
                        ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='precomputed_recommendations', to='products.product')),
                        ('user', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precomputed_recommendations', to='products.customer')),
                    ],
                    options={'db_table': 'precomputed_recommendations'},
                ),
                migrations.CreateModel(
                    name='StockMovement',
                    fields=[
                        ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('action_type', models.CharField(max_length=30)),
                        ('quantity_before', models.IntegerField()),
                        ('change_quantity', models.IntegerField()),
                        ('quantity_after', models.IntegerField()),
                        ('reason', models.CharField(max_length=255)),
                        ('note', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.order')),
                        ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.staffprofile')),
                        ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.productvariant')),
                    ],
                    options={'db_table': 'stock_movements'},
                ),
                migrations.CreateModel(
                    name='AttributeKey',
                    fields=[
                        ('attribute_key_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('code', models.CharField(max_length=100, unique=True)),
                        ('name', models.CharField(max_length=255)),
                        ('is_filterable', models.BooleanField(default=True)),
                    ],
                    options={'db_table': 'attribute_keys'},
                ),
                migrations.CreateModel(
                    name='ProductAttributeValue',
                    fields=[
                        ('attribute_value_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('value', models.CharField(max_length=255)),
                        ('attribute_key', models.ForeignKey(db_column='attribute_key_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='products.attributekey')),
                        ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
                    ],
                    options={'db_table': 'product_attribute_values'},
                ),
                migrations.CreateModel(
                    name='CouponUsage',
                    fields=[
                        ('coupon_usage_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                        ('used_at', models.DateTimeField(auto_now_add=True)),
                        ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='products.coupon')),
                        ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='products.order')),
                        ('user', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='products.customer')),
                    ],
                    options={'db_table': 'coupon_usages'},
                ),
                migrations.CreateModel(
                    name='StockReservation',
                    fields=[
                        ('reservation_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('quantity', models.IntegerField()),
                        ('status', models.CharField(max_length=30)),
                        ('expires_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.order')),
                        ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.productvariant')),
                    ],
                    options={'db_table': 'stock_reservations'},
                ),
                migrations.CreateModel(
                    name='EmailOutbox',
                    fields=[
                        ('email_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('to_email', models.CharField(max_length=254)),
                        ('subject', models.CharField(max_length=255)),
                        ('body', models.TextField()),
                        ('status', models.CharField(default='pending', max_length=30)),
                        ('error_message', models.TextField(blank=True, null=True)),
                        ('retry_count', models.IntegerField(default=0)),
                        ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                        ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                        ('sent_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('related_order', models.ForeignKey(blank=True, db_column='related_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_outbox', to='products.order')),
                        ('related_user', models.ForeignKey(blank=True, db_column='related_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_outbox', to='products.storeuser')),
                    ],
                    options={'db_table': 'email_outbox'},
                ),
                migrations.CreateModel(
                    name='PaymentWebhookLog',
                    fields=[
                        ('webhook_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('provider', models.CharField(max_length=50)),
                        ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                        ('payload', models.TextField()),
                        ('received_at', models.DateTimeField(auto_now_add=True)),
                        ('processed', models.BooleanField(default=False)),
                        ('process_message', models.TextField(blank=True, null=True)),
                        ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='products.payment')),
                    ],
                    options={'db_table': 'payment_webhook_logs'},
                ),
                migrations.AlterField(
                    model_name='searchlog',
                    name='user',
                    field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='products.customer'),
                ),
                migrations.AlterField(
                    model_name='searchlog',
                    name='query',
                    field=models.CharField(db_column='keyword', max_length=255),
                ),
                migrations.AddField(
                    model_name='searchlog',
                    name='filters',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='searchlog',
                    name='result_count',
                    field=models.IntegerField(default=0),
                ),
            ],
        ),
    ]
