# Generated by Django 5.2.6 on 2026-06-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_checkout_cart_order_integrity'),
        ('products', '0033_checkout_payment_lifecycle'),
    ]

    operations = [
    ]
